// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactASPNetCRUD.Database;

#nullable disable

namespace ReactASPNetCRUD.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220815093754_PostMigration")]
    partial class PostMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ReactASPNetCRUD.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "Something content for 1 post",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "Something content for 2 post",
                            Title = "Post 2"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "Something content for 3 post",
                            Title = "Post 3"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "Something content for 4 post",
                            Title = "Post 4"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "Something content for 5 post",
                            Title = "Post 5"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "Something content for 6 post",
                            Title = "Post 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
