const API_BASE_URL_DEVELOPMENT = "https://localhost:7056";
const API_BASE_URL_PRODUCTION = "https://localhost:7056";

const ENDPOINTS = {
  GET_ALL_POSTS: "PostGetAll",
  GET_POST_BY_ID: "PostGetById",
  CREATE_POST: "PostCreate",
  UPDATE_POST: "PostUpdate",
  DELETE_POST_BT_ID: "PostDelete"
};

const developmnet = {
  API_URL_GET_ALL_POSTS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_POSTS}`,
  API_URL_GET_POST_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_POST_BY_ID}`,
  API_URL_CREATE_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_POST}`,
  API_URL_UPDATE_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_POST}`,
  API_URL_DELETE_POST_BT_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_POST_BT_ID}`
};

const production = {
  API_URL_GET_ALL_POSTS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_POSTS}`,
  API_URL_GET_POST_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_POST_BY_ID}`,
  API_URL_CREATE_POST: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_POST}`,
  API_URL_UPDATE_POST: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_POST}`,
  API_URL_DELETE_POST_BT_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_POST_BT_ID}`,
};

const Constants = process.env.NODE_ENV === 'developmnet' ? developmnet : production;

export default Constants;
